### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dracuslayer** [ESX-Org/esx_society#10]
I am receiving an error not sure why or how to fix. i am puzzled.

`Error running system event handling function for resource esx_society: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:39: attempt to index a nil value (field '?')
stack traceback:
        server/main.lua:39: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
hitch warning: frame time of 463 milliseconds`

**Comment by RomainLanz** [comment]
Hey @dracuslayer! 👋 

Do you still have this error?

**Comment by dracuslayer** [comment]
no this error was caused due to essentialmode 5.0 im waiting to reinstall 5.0

**Comment by RomainLanz** [comment]
Since essentialmod 5 is in **beta** and shouldnt be use I'm closing this.
