### ISSUE TITLE
Error with esx_society

### ISSUE THREAD

**Issue by MisterMike99** [ESX-Org/esx_society#14]
**[       266] Error loading script server/main.lua in resource esx_society: server/main.lua:186: attempt to index a nil value (global 'ESX')
[       282] stack traceback:
[       297] 	server/main.lua:186: in main chunk
[        93] Failed to load script server/main.lua.
[      1188] Started resource esx_society**

I can't start the script help me please.

**Comment by RomainLanz** [comment]
Please, run `es_extended` before this resource.
