### ISSUE TITLE
 Washing dirty money

### ISSUE THREAD

**Issue by Pega86** [ESX-Org/esx_society#16]
When I deposit the dirty money in my taxy company, I have to wait 24h for the cleaning, but after 24h the money does not fall into the company deposit.

local society = 'taxi'
local amount = 100

where is this line inserted?

**Comment by b0hlin** [comment]
Same problem...
Idéas anyone ?

**Comment by Delux2** [comment]
I have no freaking idea how to wash money.I have 500 dollars of dirty paper but I don't understand how this system works.To be honest I would remove it from the game since its confusing... :(

**Comment by ddh3** [comment]
Its really not that hard. You take it to a boss, give them the dirty money and they wash it. It takes 24hours. 

Ask in discord for help, this isn't an issue.
