### ISSUE TITLE
Deleting 4 files?

### ISSUE THREAD

**Issue by SimonHama** [ESX-Org/esx_society#22]
Im getting an error in cmd like this: Error running system event handling function for resource esx_society: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:39: attempt to index a nil value (field '?')
stack traceback:
        server/main.lua:39: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:173>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:173: in function <citizen:/scripting/lua/scheduler.lua:138>
hitch warning: frame time of 540 milliseconds

And it's deleting 4 files... When i try to add same script again it says i have 15 files and 11 in the folder...

**Comment by ElPumpo** [comment]
Already fixed
