### ISSUE TITLE
Problem with xPlayer at start

### ISSUE THREAD

**Issue by avaloon** [ESX-Org/esx_society#23]
Hello, 
I don't touche anything on esx_society and in have this error on my consol : 
`Error running call reference function for resource esx_society: citizen:/scripting/lua/scheduler.lua:348: server/main.lua:74: attempt to index a nil value (upvalue 'xPlayer')
stack traceback:
        server/main.lua:74: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:334: in function <citizen:/scripting/lua/scheduler.lua:333>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:333: in function <citizen:/scripting/lua/scheduler.lua:332>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:348: in function <citizen:/scripting/lua/scheduler.lua:319>
        [C]: in function 'coroutine.resume'
        citizen:/scripting/lua/scheduler.lua:34: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:173: in function <citizen:/scripting/lua/scheduler.lua:138>
Error running system event handling function for resource esx_addonaccount: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:560: in local 'cb'
        server/main.lua:85: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:173>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:173: in function <citizen:/scripting/lua/scheduler.lua:138>
Error running system event handling function for resource esx_society: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:91: attempt to index a nil value (local 'xPlayer')
stack traceback:
        server/main.lua:91: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:173>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:173: in function <citizen:/scripting/lua/scheduler.lua:138>
Error running system event handling function for resource esx_society: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:111: attempt to index a nil value (local 'xPlayer')
stack traceback:
        server/main.lua:111: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:173>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:173: in function <citizen:/scripting/lua/scheduler.lua:138>
`

I have cron and esx_addonaccount start before esx_society.
Do you know why i have this error ?
I can't use the fonction withdrawMoney, depositMoney and washMoney

Best regards,
Avaloon

**Comment by ElPumpo** [comment]
Do you have esx_jobs installed? In that case see the updated database file.
