### ISSUE TITLE
Society Error 

### ISSUE THREAD

**Issue by HeQu11** [ESX-Org/esx_society#24]
Loaded MySqlConnector, Version=0.26.0.0, Culture=neutral, PublicKeyToken=null into ScriptDomain_717667050 
hitch warning: frame time of 885 milliseconds 
Loaded System.Threading.Tasks.Extensions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 into ScriptDomain_717667050 
Loaded System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 into ScriptDomain_717667050 
Error running system event handling function for resource esx_society: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:39: attempt to index a nil value (field '?') 
stack traceback: 
server/main.lua:39: in upvalue 'handler' 
citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174> 
stack traceback: 
[C]: in function 'error' 
citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow' 
citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>

**Comment by cod3rkane** [comment]
I got the same error. 
![error](https://user-images.githubusercontent.com/3195760/36945530-59414b28-1f8e-11e8-8383-bab2af5e7b29.JPG)

**Comment by HeQu11** [comment]
if this error persists adding anybody to the medics work or a police officer will be impossible!

**Comment by HeQu11** [comment]
and i have this error when i want add someone to the policejob: 
Error running call reference function for resource es_extended: citizen:/scripting/lua/scheduler.lua:351: server/classes/player.lua:330: attempt to index a nil value (field '?') 
stack traceback: 
server/classes/player.lua:330: in upvalue 'ref' 
citizen:/scripting/lua/scheduler.lua:337: in function <citizen:/scripting/lua/scheduler.lua:336> 
[C]: in function 'xpcall' 
citizen:/scripting/lua/scheduler.lua:336: in function <citizen:/scripting/lua/scheduler.lua:335> 
stack traceback: 
[C]: in function 'error' 
citizen:/scripting/lua/scheduler.lua:351: in function <citizen:/scripting/lua/scheduler.lua:322> 
[ERROR] [MySQL] Check the error above, an error happens when executing the callback from the query : "SELECT * FROM `jobs` WHERE `name` = @name {@name=police}" 
hitch warning: frame time of 162 milliseconds

**Comment by cod3rkane** [comment]
Hi @HeQu11, I fixed the error, I rebuilt my `jobs` table. probability this error occurs when we don't have all items on database.

**Comment by ElPumpo** [comment]
Caused by https://github.com/ESX-Org/esx_jobs/pull/25 or similar job.
