### ISSUE TITLE
my esx_society does not work

### ISSUE THREAD

**Issue by crocrodail** [ESX-Org/esx_society#3]
My problem occurred when I added a person chief of police:

Error running call reference function for resource esx_society: server/main.lua:77: attempt to index a nil value (local 'account')
stack traceback:
        server/main.lua:77: in local 'ref'
        citizen:/scripting/lua/scheduler.lua:278: in function <citizen:/scripting/lua/scheduler.lua:269>
        [C]: in upvalue '_in'
        citizen:/scripting/lua/natives_server.lua:243: in function 'TriggerEventInternal'
        (...tail calls...)
        server/main.lua:76: in local 'ref'
        citizen:/scripting/lua/scheduler.lua:278: in function <citizen:/scripting/lua/scheduler.lua:269>
Error running system event handling function for resource esx_addonaccount: citizen:/scripting/lua/scheduler.lua:39: Failed to execute thread: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:339: in local 'cb'
        server/main.lua:85: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:124: in function <citizen:/scripting/lua/scheduler.lua:123>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:39: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:123: in function <citizen:/scripting/lua/scheduler.lua:92>

**Comment by RomainLanz** [comment]
Hey @crocrodail! 👋 

Do you still have your issue?

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter
