### ISSUE TITLE
withdraw society and deposit society

### ISSUE THREAD

**Issue by Hubal82** [ESX-Org/esx_society#31]
Error; Deposit maney - Job Mechanic

Error running system event handling function for resource esx_society: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:110: attempt to index a nil value (local 'society')
stack traceback:
        server/main.lua:110: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>

**Comment by ElPumpo** [comment]
Stack traces by esx_society means that you have scripts that aren't properly configured.
