### ISSUE TITLE
How to remove

### ISSUE THREAD

**Issue by morzgore** [ESX-Org/esx_society#34]
Hey, i wanna know how can i remove people from setting themselfs salary and moneywash ? I've tried myself to remove it but when i do it.. then the menu doesn't open anymore.. so can you help me out ?

**Comment by Davedd123** [comment]
in society config it says max salary change that to 0 or remove it

**Comment by morzgore** [comment]
I think you don't understand

**Comment by ElPumpo** [comment]
You can already do this. Added example on readme
