### ISSUE TITLE
error

### ISSUE THREAD

**Issue by CravinGamer** [ESX-Org/esx_society#41]
i keep getting this error 

Error running system event handling function for resource esx_society: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:39: attempt to index a nil value (field '?')
stack traceback:
        server/main.lua:39: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>

**Comment by CravinGamer** [comment]
i dont know if its because ive had alot of errors about the id because most of esx script leave id so its like i dont know if thats the problem or not

**Comment by ElPumpo** [comment]
Install the scripts correctly.
