### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dragese** [ESX-Org/esx_society#42]
Error running system event handling function for resource esx_society: citizen:/
scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:98: at
tempt to index a nil value (local 'society')
stack traceback:
        server/main.lua:98: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scriptin
g/lua/scheduler.lua:174>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scriptin
g/lua/scheduler.lua:138>

**Comment by ElPumpo** [comment]
Install the scripts correctly. Or register the society in your database manually
