### ISSUE TITLE
HELP,not an issue

### ISSUE THREAD

**Issue by whitewolftbc** [ESX-Org/esx_society#44]
Hi,
how can i set the society to pay the jobs salaries..
for example the police society is paying the salaries to police employees, ambulance society - ambulance etc.
Also - is there a boss menu for the ambulance job ? i was looking at esx_ambulancejob config file but there isnt anything about boss menu etc.. EnablePlayerManagement is set to true in the config file of esx_ambulancejob

I'll be happy if someone can help me :)

Best regards

**Comment by nearbyplayer** [comment]
Please ask for help in the discord.

**Comment by ElPumpo** [comment]
Already implemented in esx?
