### ISSUE TITLE
Error with the instant money wash

### ISSUE THREAD

**Issue by AlexLeGamer** [ESX-Org/esx_society#45]
hi, i tried to do the instant money cleaning but i got this error:
```
[ERROR] [MySQL] Check the error above, an error happens when executing the callback from the query : "SELECT * FROM society_moneywash {=}"
Error running call reference function for resource esx_society: citizen:/scripting/lua/scheduler.lua:348: server/main.lua:377: attempt to index a nil value (local 'society')
stack traceback:
    server/main.lua:377: in upvalue 'ref'
    citizen:/scripting/lua/scheduler.lua:334: in function <citizen:/scripting/lua/scheduler.lua:333>
    [C]: in function 'xpcall'
    citizen:/scripting/lua/scheduler.lua:333: in function <citizen:/scripting/lua/scheduler.lua:332>
stack traceback:
    [C]: in function 'error'
    citizen:/scripting/lua/scheduler.lua:348: in function <citizen:/scripting/lua/scheduler.lua:319>
```

what to do to reproduce this error: http://prntscr.com/kj0hq1
go to esx_society/server/main.lua and at the end of this file you simply need to add what i add in the screenshot and you will get the same error as me. and i know i can simply fix this by removing all the change i have done but i would like to get a way to have the money wash instant and this is the only way i have found to do this but it does'nt work so if you could simply help me it would be nice. thank to answer me as soon as possible

**Comment by ElPumpo** [comment]
The societies arent properly registered

**Comment by AlexLeGamer** [comment]
what do you mean "the societies arent properly registered" its not the answer i was asking for can you please read all the issue and reopen this thread
