### ISSUE TITLE
Error esx_society

### ISSUE THREAD

**Issue by btwentyone** [ESX-Org/esx_society#56]
Hello,

I have a small problem, I have these errors that launches but I can not see where it comes from. Thank you

`Error running system event handling function for resource esx_society: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:26: attempt to index a nil value (field '?') 
stack traceback: 
server/main.lua:26: in upvalue 'handler' 
citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174> 
stack traceback: 
[C]: in function 'error' 
citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow' 
citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138> 
hitch warning: frame time of 597 milliseconds `

**Comment by lilfuchs** [comment]
ive seen you make a few issues. of the same errors. my guess is you installed things wrong. or have incorrect startup in the server.cfg  you can check by looking at https://esx-org.github.io/

**Comment by btwentyone** [comment]
I think my server.cfg is right :(

`#### FIVEM DEFAULT ####
start mapmanager
start chat
start spawnmanager
start sessionmanager
start fivem
start hardcap
start rconlog
start scoreboard
start loadscreen
#start playernames

#### MYSQL ASYNC
start mysql-async

#### ESSENTIAL MODS
start essentialmode
start esplugin
start es_admin2
start es_extended
start es_camera

#### ESX REQUIRED MODS
start instance
start cron
start esx_whitelist
start esx_ban
start async
start skinchanger
start esx_skin
start esx_menu_default
start esx_menu_dialog
start esx_menu_list
start gcphone
start esx_addons_gcphone
start esx_addonaccount
start esx_addoninventory
start esx_datastore
start esx_society
start esx_service
start esx_billing`

**Comment by ElPumpo** [comment]
Look at previous closed issues. You have missing sql imports in your database, or add societies manually.
