### ISSUE TITLE
I become this error today

### ISSUE THREAD

**Issue by WirkungslosYT** [ESX-Org/esx_society#57]
Error running system event handling function for resource esx_society: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:27: attempt to index a nil value (field '?')
stack traceback:
        server/main.lua:27: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>

Can anyone help me i have this error in my Console

**Comment by ElPumpo** [comment]
#56
