### ISSUE TITLE
ESX_society police garage

### ISSUE THREAD

**Issue by cantfish** [ESX-Org/esx_society#67]
Error running call reference function for resource esx_society: citizen:/scripting/lua/scheduler.lua:351: server/main.lua:307: attempt to index a nil value (local 'society')
stack traceback:
        server/main.lua:307: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:337: in function <citizen:/scripting/lua/scheduler.lua:336>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:336: in function <citizen:/scripting/lua/scheduler.lua:335>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:351: in function <citizen:/scripting/lua/scheduler.lua:322>

**Comment by ElPumpo** [comment]
Societiy garages are now deprecated.
