### ISSUE TITLE
Not a issue is only a suggestion

### ISSUE THREAD

**Issue by ElRocaYT** [ESX-Org/esx_society#7]
Would be great now what the bosses can recruit workers, that the paychecks of this workers comes from society account and substract the money of the society.

**Comment by RomainLanz** [comment]
Hey @ElRocaYT! 👋 

Yes, this is a very good suggestion and I completly agree with you.
I'm going to patch this resource to add that on my server and I'll probably also update it here too.

**Comment by indilo53** [comment]
Better create a custom paycheck file and add it in es_extened as paycheck_society.lua

**Comment by ElRocaYT** [comment]
@RomainLanz @indilo53 Guys can you check this, I'm trying to do a custom paycheck as you said but I'm not a DEV so maybe I'm typing dumb things xd
https://pastebin.com/gxAf46nU

**Comment by RomainLanz** [comment]
I got this script on my machine, just need to battle test it before release it 👍

**Comment by ElRocaYT** [comment]
OK I will wait then but only for know, the code I shared it made sense or is dumb functions? xd

**Comment by RomainLanz** [comment]
Done here https://github.com/ESX-Org/es_extended/commit/d0c822f0a6d3097d0863ee1b1eebf6537e21f903
