### ISSUE TITLE
i have error

### ISSUE THREAD

**Issue by funzik** [ESX-Org/esx_society#8]
[    893172] Error running call reference function for resource esx_society: server/main.lua:262: attempt to index a nil value (local 'xPlayer')
[    893172] stack traceback:
[    893172] 	server/main.lua:262: in local 'ref'

**Comment by RomainLanz** [comment]
Hey @funzik! 👋 

Do you still have your issue?

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter
